-- CreateTable
CREATE TABLE "Contract" (
    "id" UUID NOT NULL,
    "nrInst" TEXT NOT NULL,
    "nrAgencia" TEXT NOT NULL,
    "cdClient" TEXT NOT NULL,
    "nmClient" TEXT NOT NULL,
    "nrCpfCnpj" TEXT NOT NULL,
    "nrContrato" TEXT NOT NULL,
    "dtContrato" DATE NOT NULL,
    "qtPrestacoes" INTEGER NOT NULL,
    "vlTotal" DOUBLE PRECISION NOT NULL,
    "cdProduto" TEXT NOT NULL,
    "dsProduto" TEXT NOT NULL,
    "cdCarteira" TEXT NOT NULL,
    "dsCarteira" TEXT NOT NULL,
    "nrProposta" TEXT NOT NULL,
    "nrPresta" TEXT NOT NULL,
    "tpPresta" TEXT NOT NULL,
    "nrSeqPre" TEXT NOT NULL,
    "dtVctPre" DATE NOT NULL,
    "vlPresta" DOUBLE PRECISION NOT NULL,
    "vlMora" DOUBLE PRECISION NOT NULL,
    "vlMulta" DOUBLE PRECISION NOT NULL,
    "vlOutAcr" DOUBLE PRECISION NOT NULL,
    "vlIof" DOUBLE PRECISION NOT NULL,
    "vlDescon" DOUBLE PRECISION NOT NULL,
    "vlAtual" DOUBLE PRECISION NOT NULL,
    "idSituac" TEXT NOT NULL,
    "idSitVen" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Contract_pkey" PRIMARY KEY ("id")
);
